apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: docs-svc-plus
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
        autoscaling.knative.dev/maxScale: '20'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 266500572462-compute@developer.gserviceaccount.com
      containers:
      - name: docs-api
        image: asia-northeast1-docker.pkg.dev/xzerolab-480008/cloud-run-source-deploy/content-service/docs-svc-plus:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: KNOWLEDGE_REPO_PATH
          value: /knowledge
        - name: KNOWLEDGE_REPO_URL
          value: https://github.com/haitaopanhq/knowledge.git
        - name: KNOWLEDGE_REPO_REF
          value: main
        - name: DOCS_RELOAD_INTERVAL
          value: 5m
        - name: INTERNAL_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: internal-service-token
              key: latest
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
          tcpSocket:
            port: 8080
